/**
 * Comprehensive youth protection & child safety blacklist for German elementary reading app.
 * Covers vulgarities, sexual terms, hate speech, insults, violence, and weapons.
 */
export const BAD_WORDS_DE: readonly string[] = Object.freeze([
  // Insults & Vulgarities
  'arsch',
  'arschloch',
  'arschkriecher',
  'depp',
  'deppen',
  'idiot',
  'idioten',
  'dummkopf',
  'kacke',
  'kacken',
  'kackwurst',
  'scheisse',
  'scheiße',
  'scheiss',
  'scheiß',
  'scheissdreck',
  'scheißdreck',
  'pisse',
  'pissen',
  'wichser',
  'wichsen',
  'hurensohn',
  'hure',
  'nutte',
  'schlampe',
  'fotze',
  'penis',
  'vagina',
  'pimmel',
  'spast',
  'spasti',
  'missgeburt',
  'vollidiot',
  'bastard',
  'miststueck',
  'miststück',
  'penner',
  'ficker',
  'ficken',
  'gefickt',
  'abfuck',
  'drecksack',
  'wixer',
  'saukerl',
  'sauhund',
  'arschgesicht',
  'scheisskerl',
  'scheißkerl',
  'hanswurst',
  'arschgeige',
  'vollpfosten',
  'kackbratze',
  'spastiker',
  'trottel',
  'blödmann',
  'bloedmann',
  'mistkerl',

  // Extremism & Hate Speech
  'hitler',
  'nazi',
  'neger',
  'kanake',
  'judensau',
  'hakenkreuz',
  'faschist',
  'ku-klux-klan',
  'siegheil',

  // Weapons & Violence
  'messer',
  'pistole',
  'revolver',
  'gewehr',
  'flinte',
  'dolch',
  'schwert',
  'bombe',
  'granate',
  'dynamit',
  'waffe',
  'waffen',
  'toeten',
  'töten',
  'getoetet',
  'getötet',
  'umbringen',
  'umgebracht',
  'ermorden',
  'morden',
  'mord',
  'blutbad',
  'krieg',
  'sterben',
  'gestorben',
  'tod',
  'toter',
  'leiche',
  'folter',
  'foltern',
  'vergasen',
  'erschlagen',
  'abstechen',
  'erschiessen',
  'erschießen',
  'sprengen',
  'sprengstoff',
  'terror',
  'terrorist',
  'amok',
  'amoklauf',
  'blut',
  'hinrichtung',
  'koepfen',
  'köpfen',

  // Drugs & Substances
  'kokain',
  'heroin',
  'koks',
  'weed',
  'gras',
  'cannabis',
  'alkohol',
  'drogen',
  'spritze',
  'meth',
  'joint',
]);

/**
 * Checks if a given input contains or matches any bad word.
 */
export function containsBadWord(input: string): boolean {
  if (!input) return false;
  const normalized = input.trim().toLowerCase();
  return BAD_WORDS_DE.some((badWord) => normalized.includes(badWord));
}
